public class TestExceptionHandling{
    public static void main(String[] args){
        try{
            int divideByZero =100/0;
            System.out.println("Inside the block");
        } catch(ArithmeticException exception){
            System.out.println("Divide by zero condition");
        }
        
    }
}
